services:
  web:
    build:
      context: ./web_app
      dockerfile: Dockerfile
    ports:
      - "3010:3010"
    volumes:
      - ./web_app:/app
      # docker-compose.override.yml
    command: bundle exec rails server -b 0.0.0.0 -p 3010
 
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:venkatesh@db:5432/device_manager
      RAILS_ENV: production
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: venkatesh
      POSTGRES_HOST: postgres
      RAILS_MASTER_KEY: "e0c91999021681e45fbd887b3cf34201"
