
services:

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: device_manager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: venkatesh
    volumes:
      - thermostat_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    build:
      context: .
    ports:
      - "3010:3010"
      - "50051:50051"
    depends_on:
      - db
      - redis
    environment:
      - PG_HOST=db
      - PG_USER=postgres
      - PG_PASSWORD=venkatesh
      - PG_DB=device_manager
      - PG_PORT=5432
      - REDIS_URL=redis://redis:6379/1
   
    image: rails-placeholder


  influxdb:
    image: influxdb:1.8
    environment:
      INFLUXDB_DB: k6
    volumes:
      - influxdb_data:/var/lib/influxdb
    ports:
      - "8086:8086"

  grafana:
    image: grafana/grafana
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"

  grpc:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - kafka
    ports:
      - "7778:7777"
    #volumes:
    #  - .:/app
    environment:
      - GO_ENV=development

  kafka:
    image: confluentinc/cp-kafka:7.2.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8081:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    depends_on:
      - kafka
      - zookeeper
  anycable:
    image: anycable/anycable-go
    ports:
      - "3334:8080" # This is the public WebSocket port
    environment:
      - ANYCABLE_REDIS_URL=redis://redis:6379/1
      - ANYCABLE_RPC_HOST=web:50051
      - ANYCABLE_LOG_LEVEL=debug
      - ANYCABLE_DEBUG=true
      - ANYCABLE_HOST=0.0.0.0 
    depends_on:
      - redis
      - web

 

volumes:
  thermostat_db_data:
  influxdb_data:
  grafana_data:
