apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: device-manager
  region: ap-south-1

addons:
  - name: aws-ebs-csi-driver
    version: latest
    podIdentityAssociations:
      - namespace: kube-system
        serviceAccountName: ebs-csi-controller-sa
        roleARN: arn:aws:iam::109038806414:role/AmazonEKS_EBS_CSI_Driver_PodIdentityRole

