default: &default
  adapter: postgresql
  encoding: unicode
  host: postgres
  username: postgres
  password: venkatesh
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: device_manager_development



test:
  <<: *default
  database: device_manager_test
  host: <%= ENV.fetch("PG_HOST", "localhost") %>
  username: <%= ENV.fetch("PG_USER", "postgres") %>
  password: <%= ENV.fetch("PG_PASSWORD", "venkatesh") %>
  port: <%= ENV.fetch("PG_PORT", 5432) %>


production:
  <<: *default
  database: device_manager_production
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV["DATABASE_HOST"] %>
  pool: 30

cable:
  <<: *default
  database: device_manager_production_cable
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV["DATABASE_HOST"] %>
queue:
  <<: *default
  database: device_manager_production_queue
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV["DATABASE_HOST"] %>
cache:
  <<: *default
  database: device_manager_production_cache
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV["DATABASE_HOST"] %>

